import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ttsRouter from "./tts";
import authRouter from "./auth";
import enrollmentsRouter from "./enrollments";
import adminRouter from "./admin";
import adminStatsRouter from "./admin-stats";
import adminEmailRouter from "./admin-email";
import ssoRouter from "./sso";
import englishRouter from "./english";
import faqsRouter from "./faqs";
import coursesRouter from "./courses";
import certificatesRouter from "./certificates";
import checkoutRouter from "./checkout";
import storageRouter from "./storage";
import liveSessionsRouter from "./live-sessions";
import supportRouter from "./support";
import chatRouter from "./chat";
import chatAiRouter from "./chat-ai";
import chatAiTranslateRouter from "./chat-ai-translate";
import chatAiExplainRouter from "./chat-ai-explain";
import chatAiNotesRouter from "./chat-ai-notes";
import chatAiAnalyticsRouter from "./chat-ai-analytics";
import chatAiFeedbackRouter from "./chat-ai-feedback";
import englishMentorRouter from "./english-mentor";
import englishMentorFlashcardsRouter from "./english-mentor-flashcards";
import englishChurchillRouter from "./english-churchill";
import englishOrwellRouter from "./english-orwell";
import englishAttenboroughRouter from "./english-attenborough";
import englishHemingwayRouter from "./english-hemingway";
import englishVocabRouter from "./english-vocab";
import englishPlannerRouter from "./english-planner";
import englishEngagementRouter from "./english-engagement";
import adminContentRouter from "./admin-content";
import cartRouter from "./cart";
import discountRouter from "./discount";
import lexoFlashcardsCardsRouter from "./lexo-flashcards-cards";
import englishCurriculumAdminRouter from "./english-curriculum-admin";
import englishCurriculumRouter from "./english-curriculum";
import englishAnalyticsRouter from "./english-analytics";
import englishInterventionsRouter from "./english-interventions";
import englishAdaptiveRouter from "./english-adaptive";

const router: IRouter = Router();

router.use(healthRouter);
router.use(ttsRouter);
router.use(authRouter);
router.use(enrollmentsRouter);
router.use(adminRouter);
router.use(adminStatsRouter);
router.use(adminEmailRouter);
router.use(ssoRouter);
router.use(englishRouter);
router.use(faqsRouter);
router.use(coursesRouter);
router.use(certificatesRouter);
router.use(checkoutRouter);
router.use(storageRouter);
router.use(liveSessionsRouter);
router.use(supportRouter);
router.use(chatRouter);
router.use(chatAiRouter);
router.use(chatAiTranslateRouter);
router.use(chatAiExplainRouter);
router.use(chatAiNotesRouter);
router.use(chatAiAnalyticsRouter);
router.use(chatAiFeedbackRouter);
router.use(englishMentorRouter);
router.use(englishMentorFlashcardsRouter);
router.use(englishChurchillRouter);
router.use(englishOrwellRouter);
router.use(englishAttenboroughRouter);
router.use(englishHemingwayRouter);
router.use(englishVocabRouter);
router.use(englishPlannerRouter);
router.use(englishEngagementRouter);
router.use(adminContentRouter);
router.use(cartRouter);
router.use(discountRouter);
router.use(lexoFlashcardsCardsRouter);
router.use(englishCurriculumAdminRouter);
router.use(englishCurriculumRouter);
router.use(englishAnalyticsRouter);
router.use(englishInterventionsRouter);
router.use(englishAdaptiveRouter);

export default router;
